import AppKit

// Phase 57 / PRIV-01 — the ONE file in the project that touches `NSPasteboard.general`
// directly (mirrors NowPlayingMonitor's/FocusModeMonitor's "isolate the fragile system
// surface behind one file" discipline). There is no notification API for pasteboard
// changes, so this monitor polls, exactly like FocusModeMonitor polls Focus/DND state.
//
// Owner: `AppDelegate` (Plan 57-02) — the one deliberate ownership deviation
// ARCHITECTURE.md flags for this monitor; every other Monitor in this codebase is
// owned by the notch window's controller, this one is menu-bar-only glue.
@MainActor
final class ClipboardMonitor {
    // The private marker type Phase 58's real click-to-restore write will tag itself
    // with, so poll() never re-ingests its own future write (Pitfall 1's self-capture
    // loop, Maccy's proven marker-type fix). This plan only defines and consumes the
    // constant — it never writes it (Plan 57-02's DEBUG hook simulates a write of it
    // for on-device proof).
    static let restoreMarkerType = NSPasteboard.PasteboardType("com.islet.clipboardhistory.restored")

    // nonisolated(unsafe) so the owner's nonisolated deinit can call stop() — mirrors
    // FocusModeMonitor.timer/running exactly.
    private nonisolated(unsafe) var timer: DispatchSourceTimer?
    private nonisolated(unsafe) var running = false

    private var lastChangeCount: Int
    private let onChange: (ClipboardItem) -> Void

    init(onChange: @escaping (ClipboardItem) -> Void) {
        self.onChange = onChange
        // Seed the baseline from the CURRENT count at construction time, NOT 0, so
        // anything already on the pasteboard before start() is never captured as a
        // false-positive first tick (ARCHITECTURE.md's Launch Flow note).
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard !running else { return }   // idempotent — never double-schedule.
        running = true
        let t = DispatchSource.makeTimerSource(queue: .main)
        // 500ms per Maccy's proven default (PITFALLS.md Pitfall 2, STACK.md) — NOT
        // FocusModeMonitor's 2.5s, since clipboard copies are far more time-sensitive.
        t.schedule(deadline: .now(), repeating: 0.5, leeway: .milliseconds(100))
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    private func poll() {
        let pb = NSPasteboard.general
        // Cheap gate FIRST — nothing below this line runs unless the count actually
        // changed. Never reads pasteboard content unconditionally (Pitfall 2).
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        guard !isConcealedOrTransient(types),
              !isSelfCaptureMarker(types, markerType: ClipboardMonitor.restoreMarkerType) else { return }

        let string = pb.string(forType: .string)
        // .tiff checked first, .png fallback — STACK.md's documented image-read priority.
        let imageData = pb.data(forType: .tiff) ?? pb.data(forType: .png)
        guard let kind = classifyPasteboardContent(string: string, imageData: imageData) else { return }

        onChange(ClipboardItem(id: UUID(), kind: kind, timestamp: Date()))
    }

    // D-07: macOS 15.4+'s pasteboard-access privacy gate (PITFALLS.md Pitfall 6) — the
    // deployment target is 15.0, one minor version below where this API shipped, hence
    // the availability guard. Returns true only when access is NOT always-allowed;
    // false (nothing to explain) on macOS below 15.4.
    static var needsAccessExplanation: Bool {
        if #available(macOS 15.4, *) {
            return NSPasteboard.general.accessBehavior != .alwaysAllow
        }
        return false
    }

    // nonisolated so the owner's nonisolated deinit can call it — mirrors
    // FocusModeMonitor.stop() exactly.
    nonisolated func stop() {
        timer?.cancel()
        timer = nil
        running = false
    }

    deinit {
        // deinit can't be @MainActor in Swift 5 mode, so it does NOT call stop() here.
        // The owner (AppDelegate) calls stop() explicitly on teardown.
    }
}

// Pure top-level functions — mirrors DragDropSupport.swift's convention exactly: plain
// value types in, plain value/Bool out, no side effects, directly unit-testable.

// Filters `org.nspasteboard.ConcealedType`/`TransientType`/`AutoGeneratedType` copies —
// PRIV-01's required baseline convention (necessary but not sufficient per Pitfall 4;
// the residual gap is covered by Phase 56's at-rest encryption, not this file).
func isConcealedOrTransient(_ types: [NSPasteboard.PasteboardType]) -> Bool {
    let rawTypes = Set(types.map(\.rawValue))
    return rawTypes.contains("org.nspasteboard.ConcealedType")
        || rawTypes.contains("org.nspasteboard.TransientType")
        || rawTypes.contains("org.nspasteboard.AutoGeneratedType")
}

// Self-capture guard (Pitfall 1) — takes markerType as a parameter so it stays a pure,
// directly-testable function with no dependency on ClipboardMonitor itself.
func isSelfCaptureMarker(_ types: [NSPasteboard.PasteboardType], markerType: NSPasteboard.PasteboardType) -> Bool {
    types.contains(markerType)
}

// Text takes priority over image when both are present on the same copy — STACK.md's
// documented tie-break rule.
func classifyPasteboardContent(string: String?, imageData: Data?) -> ClipboardItem.Kind? {
    if let string, !string.isEmpty {
        return .text(string)
    }
    if let imageData {
        return .image(imageData)
    }
    return nil
}
