import XCTest
import AppKit
@testable import Islet

// Phase 57 / PRIV-01 — regression coverage for ClipboardMonitor.swift's 3 pure
// top-level functions (isConcealedOrTransient, isSelfCaptureMarker,
// classifyPasteboardContent). Mirrors DragDropSupportTests.swift's fixture-free
// convention: one test method per behavior, no setUp/tearDown, no mocking framework.
// A fresh, uniquely-named NSPasteboard is used everywhere a real pasteboard fixture
// is needed — NEVER the real system-general pasteboard, which this would pollute.
final class ClipboardMonitorTests: XCTestCase {

    private func freshPasteboard() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("ClipboardMonitorTests-\(UUID())"))
    }

    func testIsConcealedOrTransientTrueForConcealedType() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))

        XCTAssertTrue(isConcealedOrTransient(pasteboard.types ?? []))
    }

    func testIsConcealedOrTransientTrueForTransientType() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))

        XCTAssertTrue(isConcealedOrTransient(pasteboard.types ?? []))
    }

    func testIsConcealedOrTransientTrueForAutoGeneratedType() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

        XCTAssertTrue(isConcealedOrTransient(pasteboard.types ?? []))
    }

    func testIsConcealedOrTransientFalseForPlainStringContent() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        pasteboard.setString("hello", forType: .string)

        XCTAssertFalse(isConcealedOrTransient(pasteboard.types ?? []))
    }

    func testIsSelfCaptureMarkerTrueWhenMarkerTypePresent() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        let markerType = ClipboardMonitor.restoreMarkerType
        pasteboard.setData(Data(), forType: markerType)

        XCTAssertTrue(isSelfCaptureMarker(pasteboard.types ?? [], markerType: markerType))
    }

    func testIsSelfCaptureMarkerFalseWhenMarkerTypeAbsent() {
        let pasteboard = freshPasteboard()
        pasteboard.clearContents()
        let markerType = ClipboardMonitor.restoreMarkerType
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("com.islet.clipboardhistory.somethingElse"))

        XCTAssertFalse(isSelfCaptureMarker(pasteboard.types ?? [], markerType: markerType))
    }

    func testClassifyPasteboardContentPrefersTextWhenBothPresent() {
        let kind = classifyPasteboardContent(string: "hello", imageData: Data([0x01, 0x02]))

        XCTAssertEqual(kind, .text("hello"))
    }

    func testClassifyPasteboardContentReturnsImageWhenOnlyImageDataPresent() {
        let data = Data([0x01, 0x02])
        let kind = classifyPasteboardContent(string: nil, imageData: data)

        XCTAssertEqual(kind, .image(data))
    }

    func testClassifyPasteboardContentReturnsNilWhenNeitherPresent() {
        XCTAssertNil(classifyPasteboardContent(string: nil, imageData: nil))
    }
}
